### PR TITLE
#113: + remove strings like <!-- begin snippet ...

### LINKED ISSUE #113: Comparing code snippets results in too high scores
Example: https://chat.stackoverflow.com/transcript/message/39891045#39891045
Solution:
Remove the snippet-markdownn before comparing posts

### PR DESCRIPTION
**Pull request by FelixSFD**
Strings matching the following RegEx will be removed before comparing the posts:
`<!-- begin snippet:.*-->|<!-- language:.*-->|<!-- end snippet.*-->`

fixes #113

### CODE REVIEW

**Comment by Bhargav-Rao** [comment]
Would this affect the data sent to CP in anyway?

**Comment by FelixSFD** [comment]
No. But that reminds me of something: I forgot to actually use the new method :-D

**Comment by Bhargav-Rao** [comment]
Nah, I don't think you need to use the new method here. The old method would work perfectly fine because it will unescape the HTML stuff returned. You need to use the old method itself.

**Comment by FelixSFD** [comment]
I forgot to use it _anywhere_. Even the string-comparison is using the full markdown :-D

**Pull request merged**
