### PR TITLE
Feature/75 standby mode

### LINKED ISSUE #75: Add standby-mode
Guttenberg should check on Redunda, if it should be on standby or running

### PR DESCRIPTION
**Pull request by FelixSFD**
Implemented https://github.com/SOBotics/Redunda-lib-java

Most of the commands are blocked, when in standby, but some like `alive` do always respond.

---

Closes #75

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
/me will review when you're done fixing CI

**Comment by FelixSFD** [comment]
Switched to the snapshot of redunda-lib for now. That works

Closes #75

**Comment by FelixSFD** [comment]
Wait. Something is not working. Guttenberg is stuck in standby

**Comment by FelixSFD** [comment]
I had to install a certificate on my Raspberry Pi to connect to Redunda: http://stackoverflow.com/a/36874647/4687348

**Pull request merged**
